#' @title Visualize the PIP and credible sets generated by XMAP
#' @description This function visualizes the credible sets and PIP of XMAP output
#'
#' @param pip A p-vector of SNP PIPs, obtained wiht get_pip.
#' @param cs A list in which each list element with a vector containing the indices of the SNPs in the CS. Obtained with get_CS.
#' @param ... Additional arguments of plot function
#' 
#'
#' @examples
#' See vignette.
#' @export
plot_CS <- function(pip, cs, b = NULL,...) {
  color = c(
    "dodgerblue2",
    "green4",
    "#6A3D9A", # purple
    "#FF7F00", # orange
    "gold1",
    "skyblue2", "#FB9A99", # lt pink
    "palegreen2",
    "#CAB2D6", # lt purple
    "#FDBF6F", # lt orange
    "gray70", "khaki2",
    "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
    "darkturquoise", "green1", "yellow4", "yellow3",
    "darkorange4", "brown"
  )
  plot(pip, pch = 16, ylab = 'PIP', xlab = "variable",...)
  
  for (i in 1:length(cs)) {
    points(y = pip[cs[[i]]], x = cs[[i]], col = color[i], cex = 1.5, lwd = 2.5)
  }
  if (!is.null(b)) {
    points(which(b != 0), pip[b != 0], col = 2, pch = 16)
  }
}