# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XMAP_suff <- function(XX, Xy, yty, n, K, Sigma, Omega, Sig_E, prior_weights, maxIter, tol, estimate_prior_variance, estimate_residual_variance, estimate_background_variance) {
    .Call(`_XMAP_XMAP_suff`, XX, Xy, yty, n, K, Sigma, Omega, Sig_E, prior_weights, maxIter, tol, estimate_prior_variance, estimate_residual_variance, estimate_background_variance)
}

test <- function(XX) {
    .Call(`_XMAP_test`, XX)
}

rcpparma_hello_world <- function() {
    .Call(`_XMAP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_XMAP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_XMAP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_XMAP_rcpparma_bothproducts`, x)
}

